apiVersion: v1
kind: Service
metadata:
  name: employee-api-service
spec:
  type: LoadBalancer  # Change to "ClusterIP" if internal
  selector:
    app: employee-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080